import type { ActivityLogDataTypes } from "../types/types";

export const ticketLogs: ActivityLogDataTypes[] = [
  {
    id: "log-1-001",
    ticket_id: 1,
    ticket_phase_id: null,
    event_type: "ticket_created",
    message: "(TICKET 1)",
    user_id: "Thomas Müller",
    created_at: "2025-12-03T08:45:00Z",
  },
  {
    id: "log-1-002",
    ticket_id: 1,
    ticket_phase_id: null,
    event_type: "ticket_assigned",
    message: "Ticket wurde Jochen Busse zugewiesen.",
    user_id: "Thomas Müller",
    created_at: "2025-12-03T08:45:10Z",
  },
  {
    id: "log-1-003",
    ticket_id: 1,
    ticket_phase_id: "p-1-1",
    event_type: "phase_started",
    message: "Phase gestartet: Erster Todo-Abschnitt",
    user_id: "Jochen Busse",
    created_at: "2025-12-03T08:46:00Z",
  },
  {
    id: "log-1-004",
    ticket_id: 1,
    ticket_phase_id: "p-1-1",
    event_type: "phase_completed",
    message: "Phase abgeschlossen: Erster Todo-Abschnitt",
    user_id: "Jochen Busse",
    created_at: "2025-12-03T09:30:00Z",
  },
  {
    id: "log-1-005",
    ticket_id: 1,
    ticket_phase_id: "p-1-2",
    event_type: "phase_started",
    message: "Phase gestartet: Zweiter Todo-Abschnitt",
    user_id: "Jochen Busse",
    created_at: "2025-12-03T09:31:00Z",
  },

  {
    id: "log-2-001",
    ticket_id: 2,
    ticket_phase_id: null,
    event_type: "ticket_created",
    message: "(TICKET 2) - Ticket wurde erstellt.",
    user_id: "Thomas Müller",
    created_at: "2025-12-02T14:12:00Z",
  },
  {
    id: "log-2-002",
    ticket_id: 2,
    ticket_phase_id: null,
    event_type: "ticket_assigned",
    message: "Ticket wurde Jochen Busse zugewiesen.",
    user_id: "Thomas Müller",
    created_at: "2025-12-02T14:12:15Z",
  },
  {
    id: "log-2-003",
    ticket_id: 2,
    ticket_phase_id: "p-2-1",
    event_type: "phase_started",
    message: "Phase gestartet: Erster Todo-Abschnitt",
    user_id: "Jochen Busse",
    created_at: "2025-12-02T14:13:00Z",
  },
  {
    id: "log-2-004",
    ticket_id: 2,
    ticket_phase_id: "p-2-1",
    event_type: "phase_completed",
    message: "Phase abgeschlossen: Erster Todo-Abschnitt",
    user_id: "Jochen Busse",
    created_at: "2025-12-02T15:00:00Z",
  },
  {
    id: "log-2-005",
    ticket_id: 2,
    ticket_phase_id: "p-2-2",
    event_type: "phase_started",
    message: "Phase gestartet: Zweiter Todo-Abschnitt",
    user_id: "Jochen Busse",
    created_at: "2025-12-02T15:01:00Z",
  },
  {
    id: "log-2-006",
    ticket_id: 2,
    ticket_phase_id: "p-2-2",
    event_type: "phase_file_uploaded",
    message: "Nachweis hochgeladen: Abnahmeprotokoll.pdf",
    user_id: "Jochen Busse",
    created_at: "2025-12-02T15:10:00Z",
  },
];
