import type { TicketDataTypes } from "../types/types";

export const tickets: TicketDataTypes[] = [
  {
    id: 1,
    template_id: "1f0a4d0a-604b-42db-a969-b8c73d1ccd5b",
    template_title: "Vorlage Workflow A",
    started_by: "Thomas Müller",
    assigned_to: "Jochen Busse",
    label: "Workflow A",
    status: "open",
    created_at: "2025-12-03T08:45:00Z",
    completed_at: null,

    ticket_phase: [
      {
        id: "p-1-1",
        ticket_id: 1,
        template_phase_id: "tpl-phase-1",
        title: "DYN-Erster Todo-Abschnitt",
        order_index: 1,
        status: "inProgress",
        proof_required: false,
        approval_required: false,
        startet_at: "2025-12-03T09:30:00Z",
        completed_at: null,
        approved_by: "admin",
        created_at: "2025-12-03T08:46:00Z",

        ticket_task: [
          {
            id: "t-1-1-1",
            ticket_phase_id: "p-1-1",
            template_task_id: "tpl-task-1",
            label: "DYN-Schritt 1",
            is_required: false,
            is_done: true,
            order_index: 1,
            created_at: "2025-12-03T08:46:05Z",
          },
          {
            id: "t-1-1-2",
            ticket_phase_id: "p-1-1",
            template_task_id: "tpl-task-2",
            label: "DYN-Schritt 2",
            is_required: true,
            is_done: true,
            order_index: 2,
            created_at: "2025-12-03T08:46:10Z",
          },
          {
            id: "t-1-1-3",
            ticket_phase_id: "p-1-1",
            template_task_id: "tpl-task-3",
            label: "DYN-Schritt 3",
            is_required: true,
            is_done: true,
            order_index: 3,
            created_at: "2025-12-03T08:46:15Z",
          },
          {
            id: "t-1-1-4",
            ticket_phase_id: "p-1-1",
            template_task_id: "tpl-task-4",
            label: "DYN-Schritt 4",
            is_required: true,
            is_done: true,
            order_index: 4,
            created_at: "2025-12-03T08:46:20Z",
          },
          {
            id: "t-1-1-5",
            ticket_phase_id: "p-1-1",
            template_task_id: "tpl-task-5",
            label: "DYN-Schritt 5",
            is_required: true,
            is_done: true,
            order_index: 5,
            created_at: "2025-12-03T08:46:25Z",
          },
        ],
      },

      {
        id: "p-1-2",
        ticket_id: 1,
        template_phase_id: "tpl-phase-2",
        title: "Zweiter Todo-Abschnitt",
        order_index: 2,
        status: "inProgress",
        proof_required: false,
        approval_required: false,
        startet_at: null,
        completed_at: null,
        approved_by: null,
        created_at: "2025-12-03T09:31:00Z",

        ticket_task: [
          {
            id: "t-1-2-1",
            ticket_phase_id: "p-1-2",
            template_task_id: "tpl-task-6",
            label: "Schritt 1",
            is_required: true,
            is_done: true,
            order_index: 1,
            created_at: "2025-12-03T09:31:05Z",
          },
          {
            id: "t-1-2-2",
            ticket_phase_id: "p-1-2",
            template_task_id: "tpl-task-7",
            label: "Schritt 2",
            is_required: true,
            is_done: true,
            order_index: 2,
            created_at: "2025-12-03T09:31:10Z",
          },
          {
            id: "t-1-2-3",
            ticket_phase_id: "p-1-2",
            template_task_id: "tpl-task-8",
            label: "Schritt 3",
            is_required: true,
            is_done: true,
            order_index: 3,
            created_at: "2025-12-03T09:31:15Z",
          },
          {
            id: "t-1-2-4",
            ticket_phase_id: "p-1-2",
            template_task_id: "tpl-task-9",
            label: "Schritt 4",
            is_required: true,
            is_done: true,
            order_index: 4,
            created_at: "2025-12-03T09:31:20Z",
          },
          {
            id: "t-1-2-5",
            ticket_phase_id: "p-1-2",
            template_task_id: "tpl-task-10",
            label: "Schritt 5",
            is_required: true,
            is_done: true,
            order_index: 5,
            created_at: "2025-12-03T09:31:25Z",
          },
        ],
      },

      {
        id: "p-1-3",
        ticket_id: 1,
        template_phase_id: "tpl-phase-3",
        title: "Dritter Todo-Abschnitt",
        order_index: 3,
        status: "open",
        proof_required: false,
        approval_required: false,
        startet_at: null,
        completed_at: null,
        approved_by: null,
        created_at: "2025-12-03T10:00:00Z",

        ticket_task: [
          {
            id: "t-1-3-1",
            ticket_phase_id: "p-1-3",
            template_task_id: "tpl-task-11",
            label: "Schritt 1",
            is_required: true,
            is_done: true,
            order_index: 1,
            created_at: "2025-12-03T09:31:05Z",
          },
          {
            id: "t-1-3-2",
            ticket_phase_id: "p-1-3",
            template_task_id: "tpl-task-12",
            label: "Schritt 2",
            is_required: true,
            is_done: true,
            order_index: 2,
            created_at: "2025-12-03T09:31:10Z",
          },
          {
            id: "t-1-3-3",
            ticket_phase_id: "p-1-3",
            template_task_id: "tpl-task-13",
            label: "Schritt 3",
            is_required: true,
            is_done: true,
            order_index: 3,
            created_at: "2025-12-03T09:31:15Z",
          },
          {
            id: "t-1-3-4",
            ticket_phase_id: "p-1-3",
            template_task_id: "tpl-task-14",
            label: "Schritt 4",
            is_required: true,
            is_done: true,
            order_index: 4,
            created_at: "2025-12-03T09:31:20Z",
          },
          {
            id: "t-1-3-5",
            ticket_phase_id: "p-1-3",
            template_task_id: "tpl-task-15",
            label: "Schritt 5",
            is_required: true,
            is_done: true,
            order_index: 5,
            created_at: "2025-12-03T09:31:25Z",
          },
        ],
      },
    ],
  },
  {
    id: 2,
    template_id: "3cc5e5e3-fbb0-4ca1-a841-7438c2d7f3fd",
    template_title: "Vorlage Workflow A",
    started_by: "Thomas Müller",
    assigned_to: "Jochen Busse",
    label: "Workflow A",
    status: "inProgress",
    created_at: "2025-12-02T14:12:00Z",
    completed_at: null,

    ticket_phase: [
      {
        id: "p-2-1",
        ticket_id: 2,
        template_phase_id: "tpl-phase-1",
        title: "Erster Todo-Abschnitt",
        order_index: 1,
        status: "done",
        proof_required: false,
        approval_required: false,
        startet_at: null,
        completed_at: "2025-12-02T15:00:00Z",
        approved_by: "admin",
        created_at: "2025-12-02T14:13:00Z",

        ticket_task: [
          {
            id: "t-2-1-1",
            ticket_phase_id: "p-2-1",
            template_task_id: "tpl-task-16",
            label: "Schritt 1",
            is_required: true,
            is_done: true,
            order_index: 1,
            created_at: "2025-12-03T08:46:05Z",
          },
          {
            id: "t-2-1-2",
            ticket_phase_id: "p-2-1",
            template_task_id: "tpl-task-17",
            label: "Schritt 2",
            is_required: true,
            is_done: true,
            order_index: 2,
            created_at: "2025-12-03T08:46:10Z",
          },
          {
            id: "t-2-1-3",
            ticket_phase_id: "p-2-1",
            template_task_id: "tpl-task-18",
            label: "Schritt 3",
            is_required: true,
            is_done: true,
            order_index: 3,
            created_at: "2025-12-03T08:46:15Z",
          },
          {
            id: "t-2-1-4",
            ticket_phase_id: "p-2-1",
            template_task_id: "tpl-task-19",
            label: "Schritt 4",
            is_required: true,
            is_done: true,
            order_index: 4,
            created_at: "2025-12-03T08:46:20Z",
          },
          {
            id: "t-2-1-5",
            ticket_phase_id: "p-2-1",
            template_task_id: "tpl-task-20",
            label: "Schritt 5",
            is_required: true,
            is_done: true,
            order_index: 5,
            created_at: "2025-12-03T08:46:25Z",
          },
        ],
      },

      {
        id: "p-2-2",
        ticket_id: 2,
        template_phase_id: "tpl-phase-2",
        title: "Zweiter Todo-Abschnitt",
        order_index: 2,
        status: "inProgress",
        proof_required: false,
        approval_required: false,
        startet_at: null,
        completed_at: null,
        approved_by: null,
        created_at: "2025-12-02T15:01:00Z",

        ticket_task: [
          {
            id: "t-2-2-1",
            ticket_phase_id: "p-2-2",
            template_task_id: "tpl-task-21",
            label: "Schritt 1",
            is_required: true,
            is_done: true,
            order_index: 1,
            created_at: "2025-12-03T08:46:05Z",
          },
          {
            id: "t-2-2-2",
            ticket_phase_id: "p-2-2",
            template_task_id: "tpl-task-22",
            label: "Schritt 2",
            is_required: true,
            is_done: true,
            order_index: 2,
            created_at: "2025-12-03T08:46:10Z",
          },
          {
            id: "t-2-2-3",
            ticket_phase_id: "p-2-2",
            template_task_id: "tpl-task-23",
            label: "Schritt 3",
            is_required: true,
            is_done: true,
            order_index: 3,
            created_at: "2025-12-03T08:46:15Z",
          },
          {
            id: "t-2-2-4",
            ticket_phase_id: "p-2-2",
            template_task_id: "tpl-task-24",
            label: "Schritt 4",
            is_required: true,
            is_done: true,
            order_index: 4,
            created_at: "2025-12-03T08:46:20Z",
          },
          {
            id: "t-2-2-5",
            ticket_phase_id: "p-2-2",
            template_task_id: "tpl-task-25",
            label: "Schritt 5",
            is_required: true,
            is_done: true,
            order_index: 5,
            created_at: "2025-12-03T08:46:25Z",
          },
        ],
      },

      {
        id: "p-2-3",
        ticket_id: 2,
        template_phase_id: "tpl-phase-3",
        title: "Dritter Todo-Abschnitt",
        order_index: 3,
        status: "open",
        proof_required: false,
        approval_required: false,
        startet_at: null,
        completed_at: null,
        approved_by: null,
        created_at: "2025-12-02T15:30:00Z",

        ticket_task: [
          {
            id: "t-2-3-1",
            ticket_phase_id: "p-2-3",
            template_task_id: "tpl-task-26",
            label: "Schritt 1",
            is_required: true,
            is_done: true,
            order_index: 1,
            created_at: "2025-12-03T08:46:05Z",
          },
          {
            id: "t-2-3-2",
            ticket_phase_id: "p-2-3",
            template_task_id: "tpl-task-27",
            label: "Schritt 2",
            is_required: true,
            is_done: true,
            order_index: 2,
            created_at: "2025-12-03T08:46:10Z",
          },
          {
            id: "t-2-3-3",
            ticket_phase_id: "p-2-3",
            template_task_id: "tpl-task-28",
            label: "Schritt 3",
            is_required: true,
            is_done: true,
            order_index: 3,
            created_at: "2025-12-03T08:46:15Z",
          },
          {
            id: "t-2-3-4",
            ticket_phase_id: "p-2-3",
            template_task_id: "tpl-task-29",
            label: "Schritt 4",
            is_required: true,
            is_done: true,
            order_index: 4,
            created_at: "2025-12-03T08:46:20Z",
          },
          {
            id: "t-2-3-5",
            ticket_phase_id: "p-2-3",
            template_task_id: "tpl-task-30",
            label: "Schritt 5",
            is_required: true,
            is_done: true,
            order_index: 5,
            created_at: "2025-12-03T08:46:25Z",
          },
        ],
      },
    ],
  },
  {
    id: 3,
    template_id: "e4bd4b20-8428-4e51-91e9-47d7b3796b74",
    template_title: "Vorlage Workflow A",
    started_by: "Hans Werner",
    assigned_to: "Peter Steinert",
    label: "Workflow A",
    status: "review",
    created_at: "2025-11-30T09:50:00Z",
    completed_at: null,
  },
  {
    id: 4,
    template_id: "f126cdb5-d87c-4e47-a3d4-368e8ad3aef4",
    template_title: "Vorlage Workflow B",
    started_by: "Thomas Müller",
    assigned_to: "Jochen Busse",
    label: "Workflow B",
    status: "done",
    created_at: "2025-11-28T11:20:00Z",
    completed_at: "2025-11-29T16:04:00Z",
  },
  {
    id: 5,
    template_id: "49afb981-6f46-47b4-8ab2-b7655e6fdaa4",
    template_title: "Vorlage Workflow B",
    started_by: "Hans Werner",
    assigned_to: "Peter Steinert",
    label: "Workflow B",
    status: "inProgress",
    created_at: "2025-11-26T07:15:00Z",
    completed_at: null,
  },
  {
    id: 6,
    template_id: "7a9c7a86-72bf-4ed7-a81a-dfe9b8fda411",
    template_title: "Vorlage Workflow A",
    started_by: "Thomas Müller",
    assigned_to: "Jochen Busse",
    label: "Workflow A",
    status: "open",
    created_at: "2025-11-25T10:30:00Z",
    completed_at: null,
  },
  {
    id: 7,
    template_id: "b3e3c2db-2c1a-4fd2-8cc8-c5b3cbbf234b",
    template_title: "Vorlage Workflow B",
    started_by: "Hans Werner",
    assigned_to: "Peter Steinert",
    label: "Workflow B",
    status: "inProgress",
    created_at: "2025-11-23T08:40:00Z",
    completed_at: null,
  },
  {
    id: 8,
    template_id: "5f9bd78e-d92a-4096-9b76-1d490298f154",
    template_title: "Vorlage Workflow C",
    started_by: "Thomas Müller",
    assigned_to: "Jochen Busse",
    label: "Workflow C",
    status: "open",
    created_at: "2025-11-22T14:00:00Z",
    completed_at: null,
  },
  {
    id: 9,
    template_id: "c7e3fcb7-dc98-49b8-9ede-5e9ff9f67e6e",
    template_title: "Vorlage Workflow C",
    started_by: "Hans Werner",
    assigned_to: "Peter Steinert",
    label: "Workflow C",
    status: "review",
    created_at: "2025-11-20T13:10:00Z",
    completed_at: null,
  },
  {
    id: 10,
    template_id: "def38cb6-d7ef-41e5-886d-7a697df17ce0",
    template_title: "Vorlage Workflow A",
    started_by: "Thomas Müller",
    assigned_to: "Jochen Busse",
    label: "Workflow A",
    status: "done",
    created_at: "2025-11-19T09:50:00Z",
    completed_at: "2025-11-20T15:22:00Z",
  },
  {
    id: 11,
    template_id: "a12493bb-61ac-4263-935b-6f7b6ce24c18",
    template_title: "Vorlage Workflow B",
    started_by: "Hans Werner",
    assigned_to: "Peter Steinert",
    label: "Workflow B",
    status: "open",
    created_at: "2025-11-17T10:00:00Z",
    completed_at: null,
  },
  {
    id: 12,
    template_id: "bfa143cb-680d-4c23-9a95-cfb71a89f3ec",
    template_title: "Vorlage Workflow C",
    started_by: "Thomas Müller",
    assigned_to: "Jochen Busse",
    label: "Workflow C",
    status: "inProgress",
    created_at: "2025-11-15T11:35:00Z",
    completed_at: null,
  },
  {
    id: 13,
    template_id: "9b1b7b24-a3bc-4f57-8fd6-7bbd452c5967",
    template_title: "Vorlage Workflow C",
    started_by: "Hans Werner",
    assigned_to: "Peter Steinert",
    label: "Workflow C",
    status: "done",
    created_at: "2025-11-14T08:25:00Z",
    completed_at: "2025-11-15T18:20:00Z",
  },
  {
    id: 14,
    template_id: "0bfa6173-74d0-49f0-95e0-e6f0c66e3e49",
    template_title: "Vorlage Workflow B",
    started_by: "Thomas Müller",
    assigned_to: "Jochen Busse",
    label: "Workflow B",
    status: "review",
    created_at: "2025-11-12T12:10:00Z",
    completed_at: null,
  },
  {
    id: 15,
    template_id: "3af889a1-9e4c-4fc0-b5a4-e66ae6a19b77",
    template_title: "Vorlage Workflow A",
    started_by: "Hans Werner",
    assigned_to: "Peter Steinert",
    label: "Workflow A",
    status: "inProgress",
    created_at: "2025-11-10T15:00:00Z",
    completed_at: null,
  },
  {
    id: 16,
    template_id: "5eab2ff2-51d6-4c2e-ba9c-f6a6558c53ef",
    template_title: "Vorlage Workflow C",
    started_by: "Thomas Müller",
    assigned_to: "Jochen Busse",
    label: "Workflow C",
    status: "open",
    created_at: "2025-11-08T09:45:00Z",
    completed_at: null,
  },
  {
    id: 17,
    template_id: "13ad7b04-0594-4a06-966f-7749d2fa70a1",
    template_title: "Vorlage Workflow C",
    started_by: "Hans Werner",
    assigned_to: "Peter Steinert",
    label: "Workflow C",
    status: "done",
    created_at: "2025-11-05T08:15:00Z",
    completed_at: "2025-11-06T17:42:00Z",
  },
  {
    id: 18,
    template_id: "f2ba21e1-72cb-4d14-b099-16bc2c482a9c",
    template_title: "Vorlage Workflow C",
    started_by: "Thomas Müller",
    assigned_to: "Jochen Busse",
    label: "Workflow C",
    status: "inProgress",
    created_at: "2025-11-03T13:20:00Z",
    completed_at: null,
  },
  {
    id: 19,
    template_id: "d350f0fa-d8f4-4156-9391-b1b5a18c87b3",
    template_title: "Vorlage Workflow B",
    started_by: "Hans Werner",
    assigned_to: "Peter Steinert",
    label: "Workflow B",
    status: "review",
    created_at: "2025-11-01T14:10:00Z",
    completed_at: null,
  },
  {
    id: 20,
    template_id: "e92bf5b3-afe2-4a39-9beb-629864d56451",
    template_title: "Vorlage Workflow B",
    started_by: "Thomas Müller",
    assigned_to: "Jochen Busse",
    label: "Workflow B",
    status: "done",
    created_at: "2025-10-30T10:22:00Z",
    completed_at: "2025-10-31T12:54:00Z",
  },
  {
    id: 21,
    template_id: "6db52c09-6c47-4e02-9cb2-b2e2ce97b1ff",
    template_title: "Vorlage Workflow A",
    started_by: "Hans Werner",
    assigned_to: "Peter Steinert",
    label: "Workflow A",
    status: "open",
    created_at: "2025-10-28T07:30:00Z",
    completed_at: null,
  },
  {
    id: 22,
    template_id: "7fddfa51-2d35-47cc-a587-18dbfb674c41",
    template_title: "Vorlage Workflow C",
    started_by: "Thomas Müller",
    assigned_to: "Jochen Busse",
    label: "Workflow C",
    status: "inProgress",
    created_at: "2025-10-27T14:50:00Z",
    completed_at: null,
  },
  {
    id: 23,
    template_id: "fa1c9241-25bf-4cb9-8a31-094fdb596b22",
    template_title: "Vorlage Workflow B",
    started_by: "Hans Werner",
    assigned_to: "Peter Steinert",
    label: "Workflow B",
    status: "review",
    created_at: "2025-10-25T11:00:00Z",
    completed_at: null,
  },
  {
    id: 24,
    template_id: "ce842894-f34c-443b-9a24-9e6c8b596957",
    template_title: "Vorlage Workflow A",
    started_by: "Thomas Müller",
    assigned_to: "Jochen Busse",
    label: "Workflow A",
    status: "done",
    created_at: "2025-10-23T09:05:00Z",
    completed_at: "2025-10-24T16:30:00Z",
  },
  {
    id: 25,
    template_id: "ab6971ea-93df-4a5d-a596-36d8d8f850a9",
    template_title: "Vorlage Workflow A",
    started_by: "Hans Werner",
    assigned_to: "Peter Steinert",
    label: "Workflow A",
    status: "open",
    created_at: "2025-10-22T08:25:00Z",
    completed_at: null,
  },
  {
    id: 26,
    template_id: "94c3724d-16ee-4a10-b4f1-a028d8c5238d",
    template_title: "Vorlage Workflow B",
    started_by: "Thomas Müller",
    assigned_to: "Jochen Busse",
    label: "Workflow B",
    status: "inProgress",
    created_at: "2025-10-20T15:50:00Z",
    completed_at: null,
  },
  {
    id: 27,
    template_id: "c5213bcf-0f3d-4eb9-9f66-025fc522d258",
    template_title: "Vorlage Workflow B",
    started_by: "Hans Werner",
    assigned_to: "Peter Steinert",
    label: "Workflow B",
    status: "done",
    created_at: "2025-10-18T12:40:00Z",
    completed_at: "2025-10-19T17:18:00Z",
  },
  {
    id: 28,
    template_id: "c63d441d-95de-4f49-8aa1-ba2dbe90663a",
    template_title: "Vorlage Workflow C",
    started_by: "Thomas Müller",
    assigned_to: "Jochen Busse",
    label: "Workflow C",
    status: "review",
    created_at: "2025-10-17T11:10:00Z",
    completed_at: null,
  },
  {
    id: 29,
    template_id: "1c3cd3f9-d2eb-40b5-9a66-cf7dcb82ba72",
    template_title: "Vorlage Workflow C",
    started_by: "Hans Werner",
    assigned_to: "Peter Steinert",
    label: "Workflow C",
    status: "inProgress",
    created_at: "2025-10-15T07:55:00Z",
    completed_at: null,
  },
  {
    id: 30,
    template_id: "f42c98c9-9dc8-442d-be30-25d73918a651",
    template_title: "Vorlage Workflow A",
    started_by: "Thomas Müller",
    assigned_to: "Jochen Busse",
    label: "Workflow A",
    status: "done",
    created_at: "2025-10-13T10:40:00Z",
    completed_at: "2025-10-14T14:05:00Z",
  },
];
